# Generated by Django 5.1.15 on 2026-06-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("prix_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "offre_promo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("actif", models.BooleanField(default=True)),
            ],
        ),
    ]
